# Generated by Django 4.1.7 on 2023-07-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='img/'),
        ),
    ]
