# Generated by Django 4.1.7 on 2023-06-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_icon',
            field=models.CharField(max_length=150),
        ),
    ]
