# Generated by Django 4.1.7 on 2023-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_visit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visit',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_title',
            field=models.CharField(choices=[('national', 'national'), ('worldwide', 'worldwide'), ('regional', 'regional')], max_length=50),
        ),
    ]
